### ISSUE TITLE
Custom validator that can return multiple errors 

### ISSUE THREAD

**Issue by Jacob-32587** [yassun7010/serde_valid#70]
# What
For a property using a custom validator I want to return a list of validation errors.

# Why 
Currently I'm calling a function that can return many errors. The `Validate` macro seems to restrict custom functions to returning a singular error.

# What I've tried

`main.rs`
```rust
use serde_json::json;
use serde_valid::{validation, Validate};
use zxcvbn::zxcvbn;

#[derive(Debug, serde::Deserialize, serde::Serialize, Validate)]
pub struct User {
    user_id: i64,
    username: String,
    user_email: String,
    #[validate(custom(|v| validate_password(v, &self.username, &self.user_email)))]
    password: String,
}

pub fn validate_password(password: &str, username: &str, user_email: &str) -> Result<(), validation::Error> {
    let res = zxcvbn(password, &[username, user_email]);
    match res.feedback() {
        Some(val) if res.score() <= zxcvbn::Score::Two => Err(validation::Error::Custom(json!(val).to_string())),
        _ => Ok(())
    }
}

impl User {
    pub fn new(user_id: i64, user_name: String, user_email: String, password: String) -> Self {
        Self { user_id, username: user_name, user_email, password,}
    }
}

fn main() {
    let user1 = User::new(0, String::from("Test User"), String::from("test@gmail.com"), String::from("123@testuser"));
    match user1.validate() {
        Ok(_val) => (),
        Err(err) => {
            println!("{:#}", err);
        },
    }
}
```
`cargo.toml`
```toml
[package]
name = "password_test"
version = "0.1.0"
edition = "2021"

[dependencies]
zxcvbn = { version = "3.0.1", features = ["ser"] }
serde_valid = { version = "0.22.0" }
serde = { version = "1.0.203" }
serde_json = { version = "1.0.117" }
```

The above example is where I left off, I attempted to serialize an object using  `serde_json` and set it as the `Custom` variants value. Of course this did not work since the library has no way of knowing that my string is JSON and just serializes it as a string.

If there is a way of doing what I want let me know, otherwise would it be a big ask to allow a custom validator to return a `Vec<validation::Error>` (or something similar)?

(Thank you for any help in advance, this is a really cool validation library and I can't wait to use it in my personal project)
